formatter:
  enabled: true
  indentWidth: 2
  maxLineLength: 120
  exclude:
    - "vendor/**/*"
    - "tmp/**/*"
    - "node_modules/**/*"

linter:
  enabled: true
  failLevel: error
  exclude:
    - "vendor/**/*"
    - "tmp/**/*"
    - "node_modules/**/*"
